name: Build and Deploy Website
on:
  push:
    branches:
      - main

concurrency:
  group: 'deploy-website'
  cancel-in-progress: true

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 10_000

      - name: Get Node Version
        id: node-version
        run: |
          echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Website
        env:
          NODE_ENV: production
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: website-build
          path: ./dist
          include-hidden-files: true
          retention-days: 3

      - name: Upload CI Scripts
        uses: actions/upload-artifact@v6
        with:
          name: ci-scripts
          path: ./script/ci
          retention-days: 3

  deploy:
    name: Deploy Website
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: website-build
          path: ./dist

      - name: Download CI Scripts
        uses: actions/download-artifact@v7
        with:
          name: ci-scripts
          path: ./script/ci

      - name: Deploy via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_ROOT_PATH: ${{ secrets.FTP_ROOT_PATH }}
        run: ./script/ci/deploy.sh
